### ISSUE TITLE
Not updating to latest version

### ISSUE THREAD

**Issue by mindnuts** [RisingStack/trace-nodejs#106]
Hi,

For operational reasons we are not able to update to latest NPM. We have this in our Package.json's dependency section:

"@risingstack/trace": "risingstack/trace-nodejs",

This does not install the latest version. It installs 2.2.1 as on Friday, May 6th. Can you please look into this issue?

**Comment by gergelyke** [comment]
hey @mindnuts,

actually, it is updated to the latest version, just the way [semantic release](https://github.com/semantic-release/semantic-release) works tricks you into thinking it is not. It does not update the `package.json` file in our github repo, only publishes the changes to NPM, otherwise, the build would end up in an infinite cycle.

**Comment by mindnuts** [comment]
@gergelyke Thanks for responding. But can you please explain why Trace reports our collectors as "Outdated"?

We have an automated build server which builds the docker image of our services. The "npm install" step is cached and the layer is only ever rebuilt when we change our "package.json" file. We have had so many releases in the last few days and "npm install" happened all the time but trace was never updated and on the dash board its still reported as "2.2.1".

![](https://sc-cdn.scaleengine.net/i/f35657791b1a8ca31f20cba050fe59e61.png)

To verify this claim, i did a test on my local machine. I cleaned the NPM cache before attempting it, here are the results, it installs trace-nodejs v 2.2.1:
```
sandeep︻デ┳═ーnpm -v
2.14.12
sandeep︻デ┳═ーsudo npm cache clean
[sudo] password for sandeep: 
.......
sandeep︻デ┳═ーnpm cache ls
~/.npm
sandeep︻デ┳═ーnpm i risingstack/trace-nodejs
 
> microtime@2.1.1 install /home/sandeep/node_modules/@risingstack/trace/node_modules/microtime
> node-gyp rebuild

make: Entering directory `/home/sandeep/node_modules/@risingstack/trace/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
  SOLINK_MODULE(target) Release/obj.target/microtime.node
  COPY Release/microtime.node
make: Leaving directory `/home/sandeep/node_modules/@risingstack/trace/node_modules/microtime/build'

> gc-stats@1.0.0 install /home/sandeep/node_modules/@risingstack/trace/node_modules/gc-stats
> node-gyp rebuild

make: Entering directory `/home/sandeep/node_modules/@risingstack/trace/node_modules/gc-stats/build'
  CXX(target) Release/obj.target/gcstats/src/gcstats.o
  SOLINK_MODULE(target) Release/obj.target/gcstats.node
  COPY Release/gcstats.node
make: Leaving directory `/home/sandeep/node_modules/@risingstack/trace/node_modules/gc-stats/build'

> event-loop-stats@1.0.0 install /home/sandeep/node_modules/@risingstack/trace/node_modules/event-loop-stats
> node-gyp rebuild

make: Entering directory `/home/sandeep/node_modules/@risingstack/trace/node_modules/event-loop-stats/build'
  CXX(target) Release/obj.target/eventLoopStats/src/eventLoopStats.o
  SOLINK_MODULE(target) Release/obj.target/eventLoopStats.node
  COPY Release/eventLoopStats.node
make: Leaving directory `/home/sandeep/node_modules/@risingstack/trace/node_modules/event-loop-stats/build'
@risingstack/trace@2.2.1 node_modules/@risingstack/trace
├── lodash.isnumber@3.0.3
├── node-uuid@1.4.7
├── semver@5.1.0
├── qs@6.1.0
├── debug@2.2.0 (ms@0.7.1)
├── lodash.assign@4.0.8 (lodash.rest@4.0.2, lodash.keys@4.0.6)
├── lodash.defaults@4.0.1 (lodash.rest@4.0.2, lodash.assigninwith@4.0.6)
├── bl@1.1.2 (readable-stream@2.0.6)
├── continuation-local-storage@3.1.7 (emitter-listener@1.0.1, async-listener@0.6.0)
├── lodash.flatmap@4.3.0 (lodash._baseflatten@4.2.0, lodash.map@4.3.0)
├── sync-request@3.0.1 (http-response-object@1.1.0, concat-stream@1.5.1, then-request@2.2.0)
├── microtime@2.1.1 (bindings@1.2.1, nan@2.3.3)
├── gc-stats@1.0.0 (bindings@1.2.1, nan@2.3.3)
└── event-loop-stats@1.0.0 (nan@2.3.3)

```

**Comment by gergelyke** [comment]
It happens because the collector sends the version from the `package.json` file - which has the outdated value (but you have the latest). Let me think of a solution to solve this even if you install from github.
