### ISSUE TITLE
Error: No context available. ns.run() or ns.bind() must be called first.

### ISSUE THREAD

**Issue by FdezRomero** [RisingStack/trace-nodejs#107]
Today I set up 2 Express 4.x apps to use Trace. One worked OK but the other one was constantly throwing the following exception:

```
Error: "No context available. ns.run() or ns.bind() must be called first."
at node_modules/@risingstack/trace/node_modules/continuation-local-storage/context.js, Namespace.set:27
```

I couldn't find the source of the issue, so I'm not sure if there is something wrong with my setup or it is a problem related to the `continuation-local-storage` package. I had to comment the Trace code so the app would run again.

Thanks!

**Comment by gergelyke** [comment]
Hello @FdezRomero ,

is it sill an issue? Could you trace upgrading to `2.14.2` please?
