### ISSUE TITLE
Lost redis data

### ISSUE THREAD

**Issue by CatTail** [RisingStack/trace-nodejs#108]
As you can see, redis e2e test can't even pass because newly version of redis (2.6.0) use [a different way to `send_command`](https://github.com/NodeRedis/node_redis/blob/3ab19e963d5a586135bb6ae1126ac269c8ce0bf0/index.js#L869), I really doubt if trace works properly for all these libraries?

**Comment by gergelyke** [comment]
Hello @CatTail 
thanks for the reporting, checking now!

**Comment by gergelyke** [comment]
Hey @CatTail,
the latest release (2.14.0) fixes it - let me know if it works for you as well!
