### ISSUE TITLE
Where to import package

### ISSUE THREAD

**Issue by yetithefoot** [RisingStack/trace-nodejs#109]
As I understand trace wraps q and mongo somehow.
Where should I require `@risingstack/trace`?  How it works?

Before:

```javascript
require('@risingstack/trace');
// before Q and mongojs
var fs = require('fs');
var Q = require('q');
var mongojs = require('mongojs');
```

or after:

```javascript
var fs = require('fs');
var Q = require('q');
var mongojs = require('mongojs');
// after Q and mongojs
require('@risingstack/trace');
```

**Comment by gergelyke** [comment]
Hey,
you should require it as the very first line of you application. Under the hood Trace patches the module system, so when you are require `mongojs`, this is when it will be instrumented.
