### ISSUE TITLE
crash on circular references

### ISSUE THREAD

**Issue by mathieudutour** [RisingStack/trace-nodejs#120]
`JSON.stringify` crashes on circular dependencies here: https://github.com/RisingStack/trace-nodejs/blob/master/lib/agent/api/index.js#L67

Probably want to use https://github.com/isaacs/json-stringify-safe. Do you accept PR?

**Comment by szdavid92** [comment]
Hey! Thanks for reporting this issue. We accept PRs for course, however in this case I start fixing it ASAP, as it is quite urgent.

**Comment by szdavid92** [comment]
The fix was landed in v2.27.2. Thanks!
