### ISSUE TITLE
Mongoose/MongoDB instrumentation causing high CPU load

### ISSUE THREAD

**Issue by hbarcelos-revmob** [RisingStack/trace-nodejs#127]
I have an application that used to have a well defined CPU behavior.
Since we deployed Trace, it started to show a high CPU load.

![image](https://cloud.githubusercontent.com/assets/21175615/22714145/5db14536-ed72-11e6-896f-7a40fe616c7f.png)

The default metrics doesn't show anything abnormal, so I asked for a CPU profiling:

[jobs-syncCampaigns-v4-ip-172-31-46-216-22021-2017-02-07T22_08_22.919Z.cpuprofile.zip](https://github.com/RisingStack/trace-nodejs/files/759204/jobs-syncCampaigns-v4-ip-172-31-46-216-22021-2017-02-07T22_08_22.919Z.cpuprofile.zip)

The profile shows that it's something related to the `glue` module:

![image](https://cloud.githubusercontent.com/assets/21175615/22714345/3186868c-ed73-11e6-9da6-4d83436a4364.png)

![image](https://cloud.githubusercontent.com/assets/21175615/22714532/177bab18-ed74-11e6-9953-5c27635dd538.png)

Notice in the two image above that the self-time and total-time `@risingstack/trace/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:162` are the highest in the CPU profile.

Looking more closely to the profile, it seems like this is used in MongoDB/Mongoose instrumentation.

Additional info:

- We're using node@4.3.0
- We're using mongoose@4.4.7
- This service makes 11163.7 rpm to MongoDB

**Comment by hbarcelos-revmob** [comment]
For comparison reasons, here is another environment with lower load on MongoDB (5375.1 rpm):

[jobs-jds-cvr-beluga-ip-172-31-50-130-4032-2017-02-07T22_36_19.915Z.cpuprofile.zip](https://github.com/RisingStack/trace-nodejs/files/759254/jobs-jds-cvr-beluga-ip-172-31-50-130-4032-2017-02-07T22_36_19.915Z.cpuprofile.zip)

**Comment by szdavid92** [comment]
Hi! We are aware of the performance penalties incurred by [async-listener](https://github.com/othiym23/async-listener), that is used for retaining context through async callbacks for tracing. Basically every async task (node callbacks, promises, timers, process.nextTick) will add some CPU usage and latency. We are evaluating an other method based on [AsyncWrap](https://github.com/nodejs/diagnostics/blob/master/tracing/AsyncWrap/README.md#the-api) which is yet unstable, but hopefully perform better for node callbacks at least.

**Comment by hbarcelos-revmob** [comment]
Hi @szdavid92, I see.

Is it possible to disable trace without having to remove it from the dependencies?

Thank's

**Comment by szdavid92** [comment]
Yes, if you don't set either TRACE_API_KEY or TRACE_SERVICE_NAME, that will disable Trace completely. However this will mean that the agent won't report anything to our systems at all.

**Comment by hbarcelos-revmob** [comment]
Okay, I've done that after upgrading to `3.2.1` seems to work.

Thank's.
