### ISSUE TITLE
Instrumentation for ioredis does not work. trace v3.2.1

### ISSUE THREAD

**Issue by vasmg** [RisingStack/trace-nodejs#128]
I just signed up to trace and have set it up on a project.

The code runs an express server that connects to MongoDB using mongoose, and to Redis using ioredis v2.5.0, running on Node v5.12.0.

The instrumentation for express and MongoDB seem to be working correctly, but trace does not detect ioredis.

I have a custom library that uses ioredis to fire off a number of Lua script calls using the ioredis defineCommand method.

Any clues as to why I'm not getting any instrumentation?

**Comment by vasmg** [comment]
Haha, ok, so pretty much everything except the command I am using. Thanks very much for the quick response. Will you guys implement support for Lua calls?

**Comment by szdavid92** [comment]
We have to iterate on this, I can't tell an exact date for now. Basically the more people require the feature the sooner it is implemented.

**Comment by vasmg** [comment]
Sounds good. Thank you again for your help.
