### ISSUE TITLE
TypeError: agent.tracer.bind is not a function

### ISSUE THREAD

**Issue by maggit** [RisingStack/trace-nodejs#138]
Getting this error on the latest version `v3.7.0` 

```
TypeError: agent.tracer.bind is not a function
(/home/node/app/node_modules/@risingstack/trace/lib/instrumentations/trace-instrumentation-mongoose.js:13:27)
```
https://github.com/RisingStack/trace-nodejs/blob/a1cbeb458ae8f1a321f56e7d6bd91a3596b6277f/lib/instrumentations/trace-instrumentation-mongoose.js#L13

perhaps it should be: `agent.storage.bind`

https://github.com/RisingStack/trace-nodejs/blob/a1cbeb458ae8f1a321f56e7d6bd91a3596b6277f/lib/instrumentations/trace-instrumentation-mongoose.js#L25

**Comment by szdavid92** [comment]
Thanks for your report, you are absolutely right. I released the fix just now. Please update to `3.8.0`. Sorry for the inconvenience.
