### ISSUE TITLE
node-pre-gyp dependency fails to install

### ISSUE THREAD

**Issue by selfagency** [RisingStack/trace-nodejs#146]
```
D/nylon-web {dev} + $ yarn add @risingstack/trace                                                                                    
yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
error Couldn't find a package.json file in "/Users/daniel/Dev/nylon-web/node_modules/@risingstack/event-loop-stats/node_modules/node-pre-gyp"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by selfagency** [comment]
nearly a week later this is still unaddressed, rendering trace useless to me. guess it's time to cancel my account, seeing as how it does a terrible job of providing stack traces anyway.

**Comment by gergelyke** [comment]
Hello @selfagency 
sorry for the long response time - can you help me what yarn version are you using? there was a known issue with yarn (https://github.com/yarnpkg/yarn/issues/3736)

**Comment by selfagency** [comment]
0.27.5 and the same thing happens when i install with npm instead of yearn.

**Comment by gergelyke** [comment]
@selfagency can you help me what's your Node.js and npm versions are?

**Comment by selfagency** [comment]
node 6.10.2
npm 3.10.10

**Comment by gergelyke** [comment]
fixed in the latest version
